name: possessive
description: Convert a String to its possessive form
repository: https://github.com/brericha/dart_possessive
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^5.0.0
